# Generated by Django 5.2.6 on 2025-09-29 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medicines', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='api.medicinegroup', verbose_name='Groupe'),
        ),
        migrations.AddField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='api.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sold_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Vendu par'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='api.medicine', verbose_name='Médicament'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.sale', verbose_name='Vente'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='api.supplier', verbose_name='Fournisseur'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_number'], name='api_sale_sale_nu_2f4796_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['-created_at'], name='api_sale_created_c57c14_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['medicine_id'], name='api_medicin_medicin_bf61db_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['name'], name='api_medicin_name_bd7298_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['expiration_date'], name='api_medicin_expirat_26c463_idx'),
        ),
    ]
