# Generated by Django 5.2.6 on 2025-09-29 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.RegexValidator(message='Format email invalide (minuscules uniquement)', regex='^[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,}$')], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Uniquement lettres, espaces, tirets et apostrophes', regex="^[a-zA-ZÀ-ÿ\\s\\-\\']+$")], verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Uniquement lettres, espaces, tirets et apostrophes', regex="^[a-zA-ZÀ-ÿ\\s\\-\\']+$")], verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Format: +221771234567 ou 771234567', regex='^\\+?221[0-9]{9}$|^[0-9]{9}$')], verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(message='Format email invalide (minuscules uniquement)', regex='^[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,}$')], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Uniquement lettres, espaces, tirets et apostrophes', regex="^[a-zA-ZÀ-ÿ\\s\\-\\']+$")], verbose_name='Nom du fournisseur'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Format: +221771234567 ou 771234567', regex='^\\+?221[0-9]{9}$|^[0-9]{9}$')], verbose_name='Téléphone'),
        ),
    ]
