# Generated by Django 5.0.1 on 2025-10-03 20:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_client_email_alter_client_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='composition',
            field=models.TextField(blank=True, default='', verbose_name='Composition'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='consumption_type',
            field=models.CharField(blank=True, choices=[('oral', 'Oral'), ('injection', 'Injection'), ('topique', 'Topique'), ('inhalation', 'Inhalation')], default='oral', max_length=20, verbose_name='Type de consommation'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Fabricant/Commerçant'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='pharmaceutical_form',
            field=models.CharField(blank=True, choices=[('comprime', 'Comprimé'), ('gelule', 'Gélule'), ('sirop', 'Sirop'), ('creme', 'Crème'), ('pommade', 'Pommade'), ('injection', 'Injection'), ('gouttes', 'Gouttes'), ('suppositoire', 'Suppositoire'), ('autre', 'Autre')], default='comprime', max_length=20, verbose_name='Forme pharmaceutique'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name="Prix d'achat (FCFA)"),
        ),
    ]
