# Generated by Django 5.2.6 on 2025-09-29 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Format email invalide (minuscules uniquement)', regex='^[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,}$')], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Format: +221771234567 ou 771234567', regex='^\\+?221[0-9]{9}$|^[0-9]{9}$')], verbose_name='Téléphone'),
        ),
    ]
