# Generated by Django 5.2.6 on 2025-09-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pharmacy_name',
        ),
    ]
