# Generated by Django 5.0.1 on 2025-09-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_pharmacy_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Utilisateur'), ('admin', 'Administrateur'), ('pharmacist', 'Pharmacien')], default='user', max_length=20, verbose_name='Rôle'),
        ),
    ]
